language: cpp
dist: trusty
git:
  submodules: false
addons:
  ssh_known_hosts:
  - github.com
before_install:
- git config --global user.name "Smile-DK"
- git config --global user.email "2236141431@qq.com"
script:
- mkdir temp
- mkdir temp/expansions
- cp -rf expansions/*.cdb temp/expansions
- cp -rf expansions/script temp/expansions
- cp -rf expansions/strings.conf temp/expansions
- cp -rf lflist.conf temp
- git clone https://github.com/purerosefallen/ygopro-7210srv
- cp -rf ygopro-7210srv/cards.cdb temp
- cp -rf ygopro-7210srv/strings.conf temp
- rm -rf ygopro-7210srv
- git checkout master
- cp -rf temp/expansions .
- cp -rf temp/cards.cdb .
- cp -rf temp/lflist.conf .
- cp -rf temp/strings.conf .
- rm -rf temp
- git add . -A
- git commit -m "Push by Travis"
- git push https://Smile-DK:qawsqaws1@github.com/purerosefallen/ygopro-222DIY master
